project_id = "upfapfohwnkiugvebujh"

[functions.create-customer]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.handle-new-notification]
verify_jwt = false

[functions.monitoring-url-status]
verify_jwt = false

[functions.notify-status-change]
verify_jwt = false

[functions.send-activation-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.test-stripe-coupon]
verify_jwt = false

[functions.toggle-user-ban]
verify_jwt = false